#!/bin/sh

if [ -e /etc/gps.conf ]; then
	. /etc/gps.conf
fi

case "$1" in
	start)
		if [ "$enabled" = "true" ]; then
			echo "Starting GPS daemon..."
			gps $port $baudrate
		else
			echo "GPS service is disabled in /etc/zerotier.conf."
			exit 1
		fi
		;;

	stop)
		echo "Stopping GPS daemon..."
		killall -q gps
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
