#!/bin/sh

DAEMON="gps"
PIDFILE="/var/run/$DAEMON.pid"

if [ -e /etc/gps.conf ]; then
	. /etc/gps.conf
fi

DAEMON_ARGS="-p $port -b $baudrate -s"

case "$1" in
start)
	if [ "$enabled" = "true" ]; then
		echo "Starting GPS daemon..."
		start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
		if [ $? -eq 0 ]; then
			echo "OK"
		else
			echo "FAIL"
		fi
	else
		echo "GPS service is disabled in /etc/gps.conf"
		exit 1
	fi
	;;

stop)
	echo "Stopping GPS daemon..."
	start-stop-daemon -K -q -p "$PIDFILE"
	if [ $? -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	;;

*)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac
